services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app  # Mapeia o diretório do projeto local para o contêiner # Cache das dependências Maven
    environment:
      - MAVEN_OPTS=-Dspring-boot.run.profiles=dev
    command: mvn spring-boot:run